# MariaDB 이미지를 기본으로 사용
FROM mariadb:latest

# Python 및 기타 패키지 설치 (필요한 경우에만)
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv

# 가상환경 생성 및 활성화
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

# Python 패키지 설치
RUN pip install --upgrade pip
RUN pip install beautifulsoup4 fredapi pykrx yfinance pymysql==1.1.1 faker

# 초기화 스크립트 복사
COPY DB_setting.py /docker-entrypoint-initdb.d/
COPY database_id.txt /docker-entrypoint-initdb.d/
COPY init.sql /docker-entrypoint-initdb.d/


# 포트 설정
EXPOSE 3306
