name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Docker Compose 버전 확인

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: SSH into EC2 and deploy
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > ec2_key.pem
        chmod 400 ec2_key.pem
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} "\
          cd ~/aicc_project && \
          git pull && \
          docker-compose down && \
          docker-compose up -d"
